
import type {Metadata} from 'next';
import './globals.css';
import { Toaster } from "@/components/ui/toaster";
import AuthRefresher from '@/components/auth-refresher';

export const metadata: Metadata = {
  title: 'Sales Lead Management',
  description: 'Generated by Firebase Studio',
  icons: {
    icon: 'https://play-lh.googleusercontent.com/bXqMt9ROsGd0H9vPhib5hG-0NB-EJcAwZy6UUDhvlP-ykE595IMQtzr14R6IRWtJiGTh=w600-h300-pc0xffffff-pd',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <AuthRefresher />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
