
import type {Metadata} from 'next';
import './globals.css';
import { Toaster } from "@/components/ui/toaster";
import AuthRefresher from '@/components/auth-refresher';

export const metadata: Metadata = {
  title: 'Sales Lead Management',
  description: 'Generated by Firebase Studio',
  icons: {
    icon: 'https://www.2merkato.com/images/stories/NIB_Logo.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <AuthRefresher />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
